site_name: 3Liz Documentation
site_author: 3Liz
site_description: Ressources for 3Liz projects
site_url: https://docs.3liz.org/
copyright: '<span class="copyleft">&copy;</span> 3Liz'

site_dir: build

nav:
    - Home: index.md
    - Lizmap: lizmap.md
    - QGIS Plugins: plugins.md
    - Tools: tools.md
    - Presentations: talks.md
    - Tutorials:
        - 'Index': 'tutorial/index.md'
        - 'Filezilla 🇬🇧': 'tutorial/filezilla-en.md'
        - 'Filezilla 🇫🇷': 'tutorial/filezilla-fr.md'
        - 'WinSCP 🇬🇧': 'tutorial/winscp-en.md'
        - 'WinSCP 🇫🇷': 'tutorial/winscp-fr.md'
        - 'QGIS Repository 🇬🇧': 'tutorial/qgis-repository-en.md'
        - 'QGIS Repository 🇫🇷': 'tutorial/qgis-repository-fr.md'
        - 'Resources sharing 🇬🇧': 'tutorial/resources-sharing-en.md'
        - 'Resources sharing 🇫🇷': 'tutorial/resources-sharing-fr.md'
    - Internships:
        - GSOC: 'internships/gsoc.md'
    - Workshops FR:
        - Index: 'workshop/workshop.md'
        - Introduction: 'workshop/fr/lizmap-short-01-intro.md'
        - Première carte: 'workshop/fr/lizmap-short-02-first-map.md'
        - Légende: 'workshop/fr/lizmap-short-03-legend.md'
        - Interactions: 'workshop/fr/lizmap-short-04-popups.md'
        - Table attributaire: 'workshop/fr/lizmap-short-05-attribute-table.md'
        - Édition: 'workshop/fr/lizmap-short-06-editing.md'
        - Impression PDF: 'workshop/fr/lizmap-short-07-print.md'
        - Dataviz: 'workshop/fr/lizmap-short-08-dataviz.md'
    - Workshops EN:
        - Lizmap English: 'workshop/lizmap-short-english.md'
        - Lizmap: 'workshop/lizmap.md'
    - Links: 'links.md'

plugins:
  - search
#  - git-revision-date-localized
  - material-plausible

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition:
  - attr_list:
  - meta:
  - pymdownx.details:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.keys:
  - pymdownx.magiclink:
  - pymdownx.progressbar:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
  - pymdownx.snippets:

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - https://unpkg.com/mermaid@9.2.2/dist/mermaid.min.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css
  - media/progress_bar.css

theme:
  name: material
  font: false
  icon:
    repo: fontawesome/brands/github-alt
  language: 'en'
  logo: media/logo.png
  favicon: media/logo.png
  palette:
    accent: deep-orange
    primary: green
    scheme: preference
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/3LIZ_news

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/3liz

    - icon: fontawesome/brands/github
      link: https://github.com/3liz/

    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/3liz

    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCYYW2CTWR_84kB6pt2zCWbQ

  analytics:
    provider: plausible
    domain: docs.3liz.org
    src: "https://analytics.3liz.com/js/script.js"
