site_name: 3Liz Documentation
site_author: 3Liz
site_description: Ressources for 3Liz projects
site_url: https://docs.3liz.org/
copyright: '<span class="copyleft">&copy;</span> 3Liz'

site_dir: build

nav:
    - Home: index.md
    - Lizmap: lizmap.md
    - QGIS Plugins: plugins.md
    - Presentations: presentations.md
    - Tutorials:
        - 'Filezilla': 'tutorial/filezilla-en.md'
        - 'QGIS Repository FR': 'tutorial/qgis-repository-fr.md'
        - 'QGIS Repository EN': 'tutorial/qgis-repository-en.md'
    - Internships:
        - GSOC: 'internships/gsoc.md'
    - Workshops:
        - QGIS-FR-2020: 'workshop/qgis-fr-2020.md'
    - Links: 'links.md'

markdown_extensions:
  # - git-revision-date:
  - toc:
      permalink: "#"
  - meta:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.superfences:
  - pymdownx.tabbed:
  - pymdownx.magiclink:
  - pymdownx.details:
  - admonition:

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css

theme:
  name: material
  font: false
  icon:
    repo: fontawesome/brands/github-alt
  language: 'en'
  logo: media/logo.png
  favicon: media/logo.png
  palette:
    accent: deep-orange
    primary: green
    scheme: preference
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/3LIZ_news

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/3liz

    - icon: fontawesome/brands/github
      link: https://github.com/3liz/

    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/3liz
